import { useCallback, useEffect, useState } from 'react'
import axios from 'axios'
import { ArrowUpRight, BriefcaseBusiness, Check, ChevronRight, FileText, History, LayoutDashboard, LoaderCircle, LogOut, Sparkles, Upload, UserRound } from 'lucide-react'
import './App.css'

const api = axios.create({ baseURL: import.meta.env.VITE_API_URL || 'http://localhost:5000/api' })
api.interceptors.request.use((config) => {
  const token = localStorage.getItem('resume_token')
  if (token) config.headers.Authorization = `Bearer ${token}`
  return config
})
const navItems = [
  { id: 'dashboard', label: 'Overview', icon: LayoutDashboard },
  { id: 'upload', label: 'Resume studio', icon: FileText },
  { id: 'jobs', label: 'Job matches', icon: BriefcaseBusiness },
  { id: 'history', label: 'History', icon: History },
]

function App() {
  const [token, setToken] = useState(localStorage.getItem('resume_token'))
  const [user, setUser] = useState(null); const [view, setView] = useState('dashboard')
  const [resume, setResume] = useState(null); const [analysis, setAnalysis] = useState(null); const [jobs, setJobs] = useState([]); const [history, setHistory] = useState([])
  const [jobsLoaded, setJobsLoaded] = useState(false)
  const [loading, setLoading] = useState(false); const [error, setError] = useState('')
  const findJobs = useCallback(async () => { if (!resume) return; setLoading(true); setError(''); try { const { data } = await api.post('/jobs/match', { resumeId: resume.id }); setJobs(data.jobs); setJobsLoaded(true); setView('jobs') } catch (e) { setError(e.response?.data?.message || 'Job search failed') } finally { setLoading(false) } }, [resume])
  useEffect(() => { if (token) api.get('/auth/me').then(({ data }) => setUser(data.user)).catch(handleLogout) }, [token])
  useEffect(() => { if (token && view === 'jobs' && resume && !jobsLoaded && !loading) findJobs() }, [token, view, resume, jobsLoaded, loading, findJobs])
  function handleLogout() { localStorage.removeItem('resume_token'); setToken(null); setUser(null); setResume(null); setAnalysis(null) }
  async function authenticate(mode, email, password) { setLoading(true); setError(''); try { const { data } = await api.post(`/auth/${mode}`, { email, password }); localStorage.setItem('resume_token', data.token); setToken(data.token); setUser(data.user) } catch (e) { setError(e.response?.data?.message || 'Authentication failed') } finally { setLoading(false) } }
  async function uploadResume(file) { setLoading(true); setError(''); try { const form = new FormData(); form.append('resume', file); const { data } = await api.post('/resume/upload', form); setResume(data.resume); setJobs([]); setJobsLoaded(false); setView('upload') } catch (e) { setError(e.response?.data?.message || 'Upload failed') } finally { setLoading(false) } }
  async function analyze(jobDescription) { setLoading(true); setError(''); try { let current = resume; if (!current.parsedData.skills.length) { const { data } = await api.post('/resume/structure', { resumeId: resume.id }); current = { ...resume, parsedData: data.parsedData }; setResume(current) } const { data } = await api.post('/resume/analyze', { resumeId: current.id, jobDescription }); setAnalysis(data); setHistory((items) => [{ ...data, date: new Date().toLocaleDateString() }, ...items]); setView('analysis') } catch (e) { setError(e.response?.data?.message || 'Analysis failed') } finally { setLoading(false) } }
  if (!token) return <AuthScreen onSubmit={authenticate} loading={loading} error={error} />
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark"><Sparkles size={17} /></span>career<span className="brand-accent">lens</span></div><div className="profile"><div className="avatar"><UserRound size={18} /></div><div><strong>{user?.email?.split('@')[0] || 'Candidate'}</strong><small>Candidate workspace</small></div></div><nav>{navItems.map(({ id, label, icon: Icon }) => <button key={id} className={view === id ? 'nav-item active' : 'nav-item'} onClick={() => setView(id)}><Icon size={18} />{label}</button>)}</nav><button className="nav-item logout" onClick={handleLogout}><LogOut size={18} />Sign out</button></aside><main className="main-content"><header className="topbar"><div><p className="eyebrow">Your career, clearer</p><h1>{view === 'dashboard' ? 'Good morning.' : navItems.find((item) => item.id === view)?.label || 'Analysis'}</h1></div><div className="status-pill"><span />Workspace live</div></header>{error && <div className="alert">{error}<button onClick={() => setError('')}>Dismiss</button></div>}{loading && <div className="loading-bar"><LoaderCircle size={16} className="spin" /> Working on it...</div>}{view === 'dashboard' && <Dashboard resume={resume} analysis={analysis} onUpload={() => setView('upload')} onJobs={findJobs} />}{view === 'upload' && <UploadView resume={resume} onUpload={uploadResume} onAnalyze={analyze} />}{view === 'analysis' && <AnalysisView analysis={analysis} onJobs={findJobs} />}{view === 'jobs' && <JobsView jobs={jobs} />}{view === 'history' && <HistoryView history={history} />}</main></div>
}
function AuthScreen({ onSubmit, loading, error }) { const [mode, setMode] = useState('login'); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); return <div className="auth-page"><div className="auth-art"><div className="brand">career<span className="brand-accent">lens</span></div><div className="art-copy"><p className="eyebrow">The sharper way forward</p><h1>Make your next move a confident one.</h1><p>Turn your resume into a strategy. Understand your fit, close the gaps, and find the roles worth your energy.</p></div><div className="quote">“The best career decisions start with a little more clarity.”</div></div><div className="auth-panel"><div className="auth-form"><p className="eyebrow">Welcome to careerlens</p><h2>{mode === 'login' ? 'Pick up where you left off.' : 'Build your career signal.'}</h2><p className="muted">{mode === 'login' ? 'Sign in to your workspace.' : 'Create a private workspace for your job search.'}</p>{error && <div className="alert">{error}</div>}<label>Email address<input type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@example.com" /></label><label>Password<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="At least 6 characters" /></label><button className="primary wide" disabled={loading} onClick={() => onSubmit(mode, email, password)}>{loading ? <LoaderCircle className="spin" size={17} /> : mode === 'login' ? 'Enter workspace' : 'Create workspace'}<ChevronRight size={17} /></button><p className="switch-auth">{mode === 'login' ? 'New here?' : 'Already have an account?'} <button onClick={() => setMode(mode === 'login' ? 'signup' : 'login')}>{mode === 'login' ? 'Create an account' : 'Sign in'}</button></p></div></div></div> }
function Dashboard({ resume, analysis, onUpload, onJobs }) { return <><section className="hero-row"><div><p className="eyebrow">Monday, September 21</p><h2>Your next chapter<br /><em>starts here.</em></h2><p className="hero-text">A focused workspace to sharpen your resume and find work that fits.</p><button className="primary" onClick={onUpload}>{resume ? 'Open resume studio' : 'Add your resume'} <ArrowUpRight size={17} /></button></div><div className="signal-card"><div className="signal-orbit"><Sparkles size={20} /></div><p className="eyebrow">Career signal</p><strong>{analysis ? `${analysis.matchScore}%` : '—'}</strong><span>{analysis ? 'latest role match' : 'Run an analysis to see your signal'}</span></div></section><section className="section-heading"><div><p className="eyebrow">Your workspace</p><h3>Keep the momentum</h3></div></section><div className="dashboard-grid"><div className="feature-card dark"><Sparkles size={22} /><h3>Resume intelligence</h3><p>{resume ? 'Your resume is ready for a thoughtful review against the role you want.' : 'Upload your resume and see what hiring teams will notice first.'}</p><button className="text-button" onClick={onUpload}>Open studio <ArrowUpRight size={15} /></button></div><div className="feature-card"><BriefcaseBusiness size={22} /><h3>Find your next role</h3><p>Discover fresh opportunities ranked around your actual experience and skills.</p><button className="text-button" disabled={!resume} onClick={onJobs}>Explore matches <ArrowUpRight size={15} /></button></div></div></> }
function UploadView({ resume, onUpload, onAnalyze }) { const [job, setJob] = useState(''); return <section className="studio"><div className="section-heading"><div><p className="eyebrow">Resume studio</p><h3>Give your experience<br />a sharper edge.</h3></div><span className="step-label">01 / 02</span></div><label className="dropzone"><input type="file" accept=".pdf,.docx,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document" onChange={(e) => e.target.files[0] && onUpload(e.target.files[0])} /><Upload size={25} /><strong>{resume ? 'Resume uploaded' : 'Drop your resume here'}</strong><span>{resume ? 'Upload another version to replace it' : 'PDF or DOCX, up to 5MB'}</span></label>{resume && <div className="resume-ready"><div className="file-icon"><FileText size={20} /></div><div><strong>Resume text extracted</strong><span>{resume.rawText.length.toLocaleString()} characters ready for analysis</span></div><Check className="check" size={19} /></div>}<div className="jd-panel"><div><p className="eyebrow">Next, choose a target</p><h3>Paste a job description</h3><p className="muted">We’ll compare your resume to the language that matters.</p></div><textarea value={job} onChange={(e) => setJob(e.target.value)} placeholder="Paste the job description here..." /><button className="primary" disabled={!resume || !job.trim()} onClick={() => onAnalyze(job)}>Analyze fit <Sparkles size={17} /></button></div></section> }
function AnalysisView({ analysis, onJobs }) { if (!analysis) return <EmptyState title="No analysis yet" />; return <section><div className="result-header"><div><p className="eyebrow">Latest analysis</p><h2>Your fit, in focus.</h2><p className="hero-text">A clear read on where your experience meets the role.</p></div><Score score={analysis.matchScore} /></div><div className="insight-grid"><Insight title="Matched skills" items={analysis.matchedSkills} tone="green" /><Insight title="Skills to build" items={analysis.missingSkills} tone="yellow" /><Insight title="ATS watchouts" items={analysis.atsIssues} tone="red" /><Insight title="Suggestions" items={analysis.suggestions} tone="plain" /></div><button className="primary" onClick={onJobs}>Find matching jobs <ArrowUpRight size={17} /></button></section> }
function Score({ score }) { return <div className="score-wrap"><div className="score"><div><strong>{score}</strong><span>/ 100</span></div></div><p>match score</p></div> }
function Insight({ title, items, tone }) { return <div className="insight"><div className={`insight-dot ${tone}`} /><h3>{title}</h3>{items?.length ? <ul>{items.map((item, i) => <li key={`${item}-${i}`}>{item}</li>)}</ul> : <p className="muted">Nothing flagged here yet.</p>}</div> }
function JobsView({ jobs }) { return <section><div className="section-heading"><div><p className="eyebrow">Fresh from the market</p><h3>Roles with a signal.</h3></div><span className="result-count">{jobs.length} matches</span></div><div className="job-grid">{jobs.map((job, i) => <article className="job-card" key={`${job.jobApplyLink}-${i}`}><div className="job-logo">{job.companyLogo ? <img src={job.companyLogo} alt="" /> : <BriefcaseBusiness size={20} />}</div><span className={`match-badge ${job.matchPercent >= 75 ? 'high' : job.matchPercent >= 50 ? 'mid' : 'low'}`}>{job.matchPercent}% match</span><h3>{job.title}</h3><p className="company">{job.companyName}</p><p className="location">{job.location} · {job.jobPublisher || 'Direct listing'}</p><a className="apply-link" href={job.jobApplyLink} target="_blank" rel="noreferrer">View role <ArrowUpRight size={15} /></a></article>)}</div>{!jobs.length && <EmptyState title="Your matches are waiting" />}</section> }
function HistoryView({ history }) { return <section><div className="section-heading"><div><p className="eyebrow">Your progress</p><h3>Analysis history.</h3></div></div>{history.length ? <div className="history-list">{history.map((item, i) => <div className="history-row" key={`${item.analysisId}-${i}`}><div className="history-icon"><FileText size={18} /></div><div><strong>Resume analysis</strong><span>{item.date} · Job description comparison</span></div><b>{item.matchScore}%</b><ChevronRight size={18} /></div>)}</div> : <EmptyState title="Your history will appear here" />}</section> }
function EmptyState({ title }) { return <div className="empty-state"><History size={24} /><h3>{title}</h3><p className="muted">Complete your first analysis to start building a clearer picture.</p></div> }
export default App
